Translation_ES
Official-MoonDao/moondaowww pull request #45
Opened 2022-01-26 11:30 UTC by irquintanas

Locale files translated into Spanish

2022-01-27 02:00 UTC, 0xb00 requested changes

2022-01-27 02:00 UTC, 0xb00 commented on i18n/es/code.json
> +  "Thanks for everyone's contributions! Our next step will be releasing TicketToSpace NFTs and sending a member to space! 🚀 🚀 🚀": {
Thank you so much @irquintanas! I generated the latest message since some of the messaging change since I think you last synced. Do you mind taking a look at these and then we can get this merged :-)

2022-01-27 10:05 UTC, irquintanas commented on i18n/es/code.json
> +  "Thanks for everyone's contributions! Our next step will be releasing TicketToSpace NFTs and sending a member to space! 🚀 🚀 🚀": {
Done!

2022-01-28 07:36 UTC, 0xb00 approved these changes

2022-01-28 07:36 UTC, merged

2022-01-28 07:50 UTC, 0xb00 commented
Thank you so much for this contribution! Looks like we missed one step to get it added to the menu bar. I opened PR #46 to get that fixed and then this should should go live :-)

2022-01-28 09:53 UTC, irquintanas commented
Great, thanks!. Glad to contribute to expanding the project..