Update index.js
Official-MoonDao/moondaowww pull request #60
Opened 2022-03-03 00:45 UTC by pmoncada

flipping the order of these, but I didn't pull this up on my terminal, just wrote directly to github. Haven't tested! But it should be fine...

2022-03-03 02:59 UTC, 0xb00 requested changes

2022-03-03 02:59 UTC, 0xb00 commented on src/pages/index.js
> +                      Release the {ticketToSpace} NFT collection. These NFTs will give you a chance to fly to space in 2022.
This need to be wrapped in the `{' message goes here ' } ` since it's using a variable. Likely why checks are failing on this PR

2022-03-03 20:48 UTC, dissentertainer commented on src/pages/index.js
> +                      Release the {ticketToSpace} NFT collection. These NFTs will give you a chance to fly to space in 2022.
@0xb00 Just to clarify, @pmoncada just needs to add single quotes around those strings, correct?

2022-03-04 21:58 UTC, 0xb00 commented on src/pages/index.js
> +                      Release the {ticketToSpace} NFT collection. These NFTs will give you a chance to fly to space in 2022.
Brackets and the single quotes, I believe.

2022-04-01 19:32 UTC, closed without merging